version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ../src/:/usr/backend_app/src
    working_dir: /usr/backend_app/
    ports:
      - "8080:8080"
    command:  bash -c 'python src/manage.py runserver 0.0.0.0:8080'
    env_file:
      - ../.env
    networks:
      - app-network
  
  database:
    image: postgres:latest
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network
    env_file:
      - ../.env
    ports:
      - 5432:5432

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: